# format_factory/gui/presets.py
"""
预设参数数据。

包含 ArgsPanel 使用的 CUSTOM_ONLY、PRESETS_BY_FMT 和 DEFAULT_FMT。
"""

# 通用备用预设（当没有专属预设时使用）
CUSTOM_ONLY = [("自定义…", "__custom__")]

# 按输出格式细分的预设
PRESETS_BY_FMT = {
# ── 视频 ──────────────────────────────────────────────────────
"mp4": [
    ("默认 (H.264 CRF23)",        []),
    ("高质量 (H.264 CRF18)",       ["-crf", "18"]),
    ("快速压缩 (H.264 CRF28)",     ["-crf", "28"]),
    ("高压缩 (H.264 CRF32)",       ["-crf", "32", "-c:a", "aac", "-b:a", "128k"]),
    ("极小体积 (H.265 CRF34)",     ["-c:v", "libx265", "-preset", "slow",
                                    "-crf", "34", "-c:a", "aac", "-b:a", "96k"]),
    ("移动端省空间 (720p)",        ["-vf", "scale=-2:720:flags=lanczos",
                                    "-c:v", "libx264", "-preset", "medium",
                                    "-crf", "30", "-c:a", "aac", "-b:a", "96k"]),
    ("平衡压缩 (H.265 CRF26)",     ["-c:v", "libx265", "-preset", "medium",
                                    "-crf", "26", "-c:a", "aac", "-b:a", "160k"]),
    ("极速编码 (ultrafast)",        ["-preset", "ultrafast", "-crf", "23"]),
    ("H.265 / HEVC (CRF28)",       ["-c:v", "libx265", "-preset", "medium",
                                    "-crf", "28", "-c:a", "aac", "-b:a", "192k"]),
    ("H.265 高质量 (CRF22)",       ["-c:v", "libx265", "-preset", "slow",
                                    "-crf", "22", "-c:a", "aac", "-b:a", "192k"]),
    ("无损 (H.264 lossless)",      ["-c:v", "libx264", "-preset", "medium",
                                    "-crf", "0", "-c:a", "pcm_s16le"]),
    ("仅视频流 (去除音频)",         ["-c:v", "copy", "-an"]),
    ("仅复制流 (超快无重编码)",     ["-c", "copy"]),
    ("自定义…",                    "__custom__"),
],
"mkv": [
    ("默认 (H.264 CRF23)",        []),
    ("高质量 (H.264 CRF18)",       ["-crf", "18"]),
    ("快速压缩 (H.264 CRF28)",     ["-crf", "28"]),
    ("高压缩 (H.264 CRF32)",       ["-crf", "32", "-c:a", "aac", "-b:a", "128k"]),
    ("极小体积 (H.265 CRF34)",     ["-c:v", "libx265", "-preset", "slow",
                                    "-crf", "34", "-c:a", "aac", "-b:a", "96k"]),
    ("平衡压缩 (H.265 CRF26)",     ["-c:v", "libx265", "-preset", "medium",
                                    "-crf", "26", "-c:a", "aac", "-b:a", "160k"]),
    ("H.265 / HEVC (CRF28)",       ["-c:v", "libx265", "-preset", "medium",
                                    "-crf", "28", "-c:a", "aac", "-b:a", "192k"]),
    ("H.265 高质量 (CRF22)",       ["-c:v", "libx265", "-preset", "slow",
                                    "-crf", "22", "-c:a", "aac", "-b:a", "192k"]),
    ("AV1 (libaom, 慢速高压缩)",   ["-c:v", "libaom-av1", "-crf", "35", "-b:v", "0",
                                    "-c:a", "libopus", "-b:a", "128k"]),
    ("AV1 极限压缩 (CRF42)",       ["-c:v", "libaom-av1", "-cpu-used", "4",
                                    "-crf", "42", "-b:v", "0",
                                    "-c:a", "libopus", "-b:a", "96k"]),
    ("无损 (H.264 lossless)",      ["-c:v", "libx264", "-preset", "medium",
                                    "-crf", "0", "-c:a", "flac"]),
    ("无损存档 (FFV1 + FLAC)",     ["-c:v", "ffv1", "-level", "3",
                                    "-c:a", "flac", "-compression_level", "8"]),
    ("仅视频流 (去除音频)",         ["-c:v", "copy", "-an"]),
    ("仅复制流 (超快无重编码)",     ["-c", "copy"]),
    ("自定义…",                    "__custom__"),
],
"mov": [
    ("默认 (H.264 CRF23)",        []),
    ("高质量 (H.264 CRF18)",       ["-crf", "18"]),
    ("高压缩 (H.264 CRF30)",       ["-c:v", "libx264", "-preset", "medium",
                                    "-crf", "30", "-c:a", "aac", "-b:a", "128k"]),
    ("预览小样 (960px)",           ["-vf", "scale=960:-2:flags=lanczos",
                                    "-c:v", "libx264", "-preset", "medium",
                                    "-crf", "32", "-c:a", "aac", "-b:a", "96k"]),
    ("ProRes 422 (专业剪辑)",      ["-c:v", "prores_ks", "-profile:v", "2",
                                    "-c:a", "pcm_s16le"]),
    ("ProRes 4444 (最高质量)",     ["-c:v", "prores_ks", "-profile:v", "4",
                                    "-c:a", "pcm_s16le"]),
    ("无损 (H.264 lossless)",      ["-c:v", "libx264", "-preset", "medium",
                                    "-crf", "0", "-c:a", "pcm_s16le"]),
    ("仅视频流 (去除音频)",         ["-c:v", "copy", "-an"]),
    ("仅复制流 (超快无重编码)",     ["-c", "copy"]),
    ("自定义…",                    "__custom__"),
],
"avi": [
    ("默认 (MPEG-4)",             []),
    ("高质量 (Q2)",               ["-c:v", "mpeg4", "-q:v", "2",
                                   "-c:a", "libmp3lame", "-q:a", "2"]),
    ("H.264 + MP3",              ["-c:v", "libx264", "-crf", "23",
                                  "-c:a", "libmp3lame", "-b:a", "192k"]),
    ("小体积 (MPEG-4 Q7)",        ["-c:v", "mpeg4", "-q:v", "7",
                                   "-c:a", "libmp3lame", "-q:a", "5"]),
    ("高压缩 (MPEG-4 Q10)",       ["-c:v", "mpeg4", "-q:v", "10",
                                   "-c:a", "libmp3lame", "-q:a", "7"]),
    ("极小体积 (H.264 CRF32)",    ["-c:v", "libx264", "-preset", "medium",
                                   "-crf", "32", "-c:a", "libmp3lame", "-b:a", "96k"]),
    ("仅视频流 (去除音频)",        ["-c:v", "copy", "-an"]),
    ("仅复制流 (超快无重编码)",    ["-c", "copy"]),
    ("自定义…",                   "__custom__"),
],
"webm": [
    ("默认 (VP9 CRF30)",          []),
    ("VP9 高质量 (CRF20)",         ["-c:v", "libvpx-vp9", "-crf", "20", "-b:v", "0",
                                    "-c:a", "libopus", "-b:a", "192k"]),
    ("VP9 快速压缩 (CRF40)",       ["-c:v", "libvpx-vp9", "-crf", "40", "-b:v", "0",
                                    "-c:a", "libopus", "-b:a", "96k"]),
    ("极致压缩 (VP9 CRF48)",       ["-c:v", "libvpx-vp9", "-crf", "48", "-b:v", "0",
                                    "-c:a", "libopus", "-b:a", "64k"]),
    ("网页分享小体积 (VP9 720p)",  ["-vf", "scale=-2:720:flags=lanczos",
                                    "-c:v", "libvpx-vp9", "-crf", "44", "-b:v", "0",
                                    "-c:a", "libopus", "-b:a", "64k"]),
    ("AV1 (libaom, 慢速高压缩)",   ["-c:v", "libaom-av1", "-crf", "35", "-b:v", "0",
                                    "-c:a", "libopus", "-b:a", "128k"]),
    ("仅视频流 (去除音频)",         ["-c:v", "libvpx-vp9", "-crf", "30", "-b:v", "0", "-an"]),
    ("自定义…",                    "__custom__"),
],
"flv": [
    ("默认 (H.264 CRF23)",        []),
    ("高质量 (CRF18)",             ["-c:v", "libx264", "-preset", "medium",
                                    "-crf", "18", "-c:a", "aac", "-b:a", "192k"]),
    ("低码率 (CRF28)",             ["-c:v", "libx264", "-preset", "fast",
                                    "-crf", "28", "-c:a", "aac", "-b:a", "96k"]),
    ("高压缩 (CRF32)",             ["-c:v", "libx264", "-preset", "medium",
                                    "-crf", "32", "-c:a", "aac", "-b:a", "80k"]),
    ("直播回放小体积 (480p)",      ["-vf", "scale=-2:480:flags=lanczos",
                                    "-c:v", "libx264", "-preset", "medium",
                                    "-crf", "31", "-c:a", "aac", "-b:a", "64k"]),
    ("仅复制流 (超快无重编码)",     ["-c", "copy"]),
    ("自定义…",                    "__custom__"),
],
"gif": [
    ("默认 (10fps 320px)",         []),
    ("高帧率 (15fps 480px)",       ["-vf", "fps=15,scale=480:-1:flags=lanczos",
                                    "-loop", "0"]),
    ("高清大图 (15fps 720px)",     ["-vf", "fps=15,scale=720:-1:flags=lanczos",
                                    "-loop", "0"]),
    ("小体积 (8fps 240px)",        ["-vf", "fps=8,scale=240:-1:flags=lanczos",
                                    "-loop", "0"]),
    ("超小体积 (6fps 160px)",      ["-vf", "fps=6,scale=160:-1:flags=lanczos",
                                    "-loop", "0"]),
    ("循环播放",                   ["-loop", "0"]),
    ("播放一次",                   ["-loop", "1"]),
    ("自定义…",                    "__custom__"),
],
# ── M3U8 ──────────────────────────────────────────────────────
"m3u8": [
    ("默认 (复制流)",              []),
    ("自定义…",                    "__custom__"),
],
# ── 音频 ──────────────────────────────────────────────────────
"mp3": [
    ("默认 (192k)",               []),
    ("高质量 (320k)",              ["-b:a", "320k"]),
    ("高质量 VBR (V0)",            ["-c:a", "libmp3lame", "-q:a", "0"]),
    ("标准 VBR (V4)",              ["-c:a", "libmp3lame", "-q:a", "4"]),
    ("低码率 (128k)",              ["-b:a", "128k"]),
    ("低码率 (96k)",               ["-b:a", "96k"]),
    ("小体积 (80k)",               ["-b:a", "80k"]),
    ("极小体积 (64k)",             ["-b:a", "64k"]),
    ("播客/语音 (48k 单声道)",     ["-ac", "1", "-b:a", "48k"]),
    ("语音压缩 (64k 单声道)",      ["-ac", "1", "-b:a", "64k"]),
    ("仅提取音频 (复制流)",         ["-c:a", "copy", "-vn"]),
    ("自定义…",                    "__custom__"),
],
"m4a": [
    ("默认 (AAC 192k)",            []),
    ("高质量 (AAC 320k)",          ["-b:a", "320k"]),
    ("无损 ALAC (Apple Lossless)", ["-c:a", "alac"]),
    ("低码率 (AAC 128k)",          ["-b:a", "128k"]),
    ("HE-AAC 小体积 (64k)",        ["-c:a", "aac", "-b:a", "64k"]),
    ("HE-AAC 极小体积 (48k)",      ["-c:a", "aac", "-b:a", "48k", "-ac", "1"]),
    ("语音备忘录 (32k 单声道)",    ["-c:a", "aac", "-b:a", "32k", "-ac", "1"]),
    ("仅提取音频 (复制流)",         ["-c:a", "copy", "-vn"]),
    ("自定义…",                    "__custom__"),
],
"aac": [
    ("默认 (192k)",               []),
    ("高质量 (320k)",              ["-b:a", "320k"]),
    ("标准 (128k)",               ["-b:a", "128k"]),
    ("低码率 (96k)",               ["-b:a", "96k"]),
    ("小体积 (64k)",               ["-b:a", "64k"]),
    ("极小体积 (48k 单声道)",      ["-b:a", "48k", "-ac", "1"]),
    ("语音压缩 (64k 单声道)",      ["-ac", "1", "-b:a", "64k"]),
    ("仅提取音频 (复制流)",         ["-c:a", "copy", "-vn"]),
    ("自定义…",                    "__custom__"),
],
"wav": [
    ("默认 (PCM 16bit)",           []),
    ("PCM 24bit",                  ["-c:a", "pcm_s24le"]),
    ("PCM 32bit",                  ["-c:a", "pcm_s32le"]),
    ("PCM 浮点 32bit",             ["-c:a", "pcm_f32le"]),
    ("广播后期 (PCM 24bit 48k)",   ["-c:a", "pcm_s24le", "-ar", "48000"]),
    ("仅提取音频 (复制流)",         ["-c:a", "copy", "-vn"]),
    ("自定义…",                    "__custom__"),
],
"flac": [
    ("默认 (压缩级别 5)",           []),
    ("最高压缩 (级别 8)",           ["-c:a", "flac", "-compression_level", "8"]),
    ("最快压缩 (级别 0)",           ["-c:a", "flac", "-compression_level", "0"]),
    ("保真存档 (级别 8)",           ["-c:a", "flac", "-compression_level", "8", "-sample_fmt", "s16"]),
    ("仅提取音频 (复制流)",         ["-c:a", "copy", "-vn"]),
    ("自定义…",                    "__custom__"),
],
"ogg": [
    ("默认 (Vorbis Q4)",           []),
    ("高质量 (Q8)",                ["-c:a", "libvorbis", "-q:a", "8"]),
    ("标准 (Q6)",                  ["-c:a", "libvorbis", "-q:a", "6"]),
    ("低码率 (Q2)",                ["-c:a", "libvorbis", "-q:a", "2"]),
    ("小体积 (Q1)",                ["-c:a", "libvorbis", "-q:a", "1"]),
    ("极小体积 (Q0 单声道)",       ["-c:a", "libvorbis", "-q:a", "0", "-ac", "1"]),
    ("语音压缩 (Q1 单声道)",       ["-c:a", "libvorbis", "-q:a", "1", "-ac", "1"]),
    ("仅提取音频 (复制流)",         ["-c:a", "copy", "-vn"]),
    ("自定义…",                    "__custom__"),
],
"opus": [
    ("默认 (96k)",                 []),
    ("高质量 (192k)",              ["-c:a", "libopus", "-b:a", "192k"]),
    ("标准 (128k)",               ["-c:a", "libopus", "-b:a", "128k"]),
    ("低码率 (64k)",               ["-c:a", "libopus", "-b:a", "64k"]),
    ("极低码率 (32k)",             ["-c:a", "libopus", "-b:a", "32k"]),
    ("超低码率 (24k)",             ["-c:a", "libopus", "-b:a", "24k"]),
    ("通话/语音 (16k 单声道)",     ["-c:a", "libopus", "-b:a", "16k", "-ac", "1"]),
    ("语音模式 (24k 单声道)",      ["-c:a", "libopus", "-b:a", "24k", "-ac", "1"]),
    ("仅提取音频 (复制流)",         ["-c:a", "copy", "-vn"]),
    ("自定义…",                    "__custom__"),
],
# ── 图片 ──────────────────────────────────────────────────────
"jpg": [
    ("默认 (Q2)",                  []),
    ("高质量 (Q1)",                ["-q:v", "1"]),
    ("标准 (Q3)",                  ["-q:v", "3"]),
    ("压缩 (Q5)",                  ["-q:v", "5"]),
    ("高压缩 (Q8)",                ["-q:v", "8"]),
    ("极限压缩 (Q12)",             ["-q:v", "12"]),
    ("无损尺寸适配 (1920px 宽)",    ["-vf", "scale=1920:-1:flags=lanczos", "-q:v", "2"]),
    ("无损尺寸适配 (1280px 宽)",    ["-vf", "scale=1280:-1:flags=lanczos", "-q:v", "2"]),
    ("缩放 1920px 宽",             ["-vf", "scale=1920:-1:flags=lanczos", "-q:v", "2"]),
    ("缩放 1280px 宽",             ["-vf", "scale=1280:-1:flags=lanczos", "-q:v", "2"]),
    ("缩放 800px 宽",              ["-vf", "scale=800:-1:flags=lanczos",  "-q:v", "2"]),
    ("缩放 512px 宽",              ["-vf", "scale=512:-1:flags=lanczos",  "-q:v", "3"]),
    ("缩放 256px 宽 (缩略图)",      ["-vf", "scale=256:-1:flags=lanczos", "-q:v", "5"]),
    ("自定义…",                    "__custom__"),
],
"png": [
    ("默认",                       []),
    ("最大压缩 (级别 9)",           ["-compression_level", "9"]),
    ("高压缩 (级别 8)",             ["-compression_level", "8"]),
    ("无压缩 (级别 0)",             ["-compression_level", "0"]),
    ("无损压缩 (级别 6)",           ["-compression_level", "6"]),
    ("缩放 1920px 宽",             ["-vf", "scale=1920:-1:flags=lanczos"]),
    ("缩放 1280px 宽",             ["-vf", "scale=1280:-1:flags=lanczos"]),
    ("缩放 800px 宽",              ["-vf", "scale=800:-1:flags=lanczos"]),
    ("缩放 512px 宽",              ["-vf", "scale=512:-1:flags=lanczos"]),
    ("缩放 256px 宽 (缩略图)",      ["-vf", "scale=256:-1:flags=lanczos"]),
    ("网页轻量图 (1280px 无损)",    ["-vf", "scale=1280:-1:flags=lanczos",
                                    "-compression_level", "9"]),
    ("自定义…",                    "__custom__"),
],
"webp": [
    ("默认 (Q85)",                 []),
    ("高质量 (Q95)",               ["-quality", "95"]),
    ("无损 WebP",                  ["-lossless", "1", "-compression_level", "6"]),
    ("无损 WebP (最大压缩)",        ["-lossless", "1", "-compression_level", "6",
                                    "-quality", "100"]),
    ("无损尺寸适配 (1280px 宽)",    ["-vf", "scale=1280:-1:flags=lanczos",
                                    "-lossless", "1", "-compression_level", "6"]),
    ("有损压缩 (Q60)",             ["-quality", "60"]),
    ("极小体积 (Q40)",             ["-quality", "40"]),
    ("超小体积 (Q25)",             ["-quality", "25"]),
    ("缩放 1920px 宽",             ["-vf", "scale=1920:-1:flags=lanczos", "-quality", "85"]),
    ("缩放 1280px 宽",             ["-vf", "scale=1280:-1:flags=lanczos", "-quality", "85"]),
    ("缩放 800px 宽",              ["-vf", "scale=800:-1:flags=lanczos",  "-quality", "85"]),
    ("缩放 512px 宽 (分享图)",      ["-vf", "scale=512:-1:flags=lanczos", "-quality", "60"]),
    ("自定义…",                    "__custom__"),
],
"bmp": [
    ("默认",                       []),
    ("缩放 1920px 宽",             ["-vf", "scale=1920:-1:flags=lanczos"]),
    ("缩放 1280px 宽",             ["-vf", "scale=1280:-1:flags=lanczos"]),
    ("缩放 800px 宽",              ["-vf", "scale=800:-1:flags=lanczos"]),
    ("缩放 512px 宽",              ["-vf", "scale=512:-1:flags=lanczos"]),
    ("缩放 256px 宽 (图标草稿)",    ["-vf", "scale=256:-1:flags=lanczos"]),
    ("自定义…",                    "__custom__"),
],
"tiff": [
    ("默认",                       []),
    ("LZW 无损压缩",               ["-compression_algo", "lzw"]),
    ("Deflate 压缩",               ["-compression_algo", "deflate"]),
    ("PackBits 压缩",              ["-compression_algo", "packbits"]),
    ("LZW 无损 + 1920px 适配",      ["-vf", "scale=1920:-1:flags=lanczos",
                                    "-compression_algo", "lzw"]),
    ("Deflate 无损 + 1280px 适配",  ["-vf", "scale=1280:-1:flags=lanczos",
                                    "-compression_algo", "deflate"]),
    ("缩放 1920px 宽",             ["-vf", "scale=1920:-1:flags=lanczos"]),
    ("缩放 1280px 宽",             ["-vf", "scale=1280:-1:flags=lanczos"]),
    ("缩放 800px 宽",              ["-vf", "scale=800:-1:flags=lanczos"]),
    ("自定义…",                    "__custom__"),
],
"ico": [
    ("默认 (256x256)",             []),
    ("128x128",                    ["-vf", "scale=128:128:flags=lanczos"]),
    ("64x64",                      ["-vf", "scale=64:64:flags=lanczos"]),
    ("32x32",                      ["-vf", "scale=32:32:flags=lanczos"]),
    ("16x16",                      ["-vf", "scale=16:16:flags=lanczos"]),
    ("自定义…",                    "__custom__"),
],
}

# 媒体类型级别的回退预设（格式没有专属预设时使用）
PRESETS = {
"video": [
    ("默认 (H.264 CRF23)",        []),
    ("高质量 (H.264 CRF18)",       ["-crf", "18"]),
    ("高压缩 (H.264 CRF30)",       ["-crf", "30", "-c:a", "aac", "-b:a", "128k"]),
    ("平衡压缩 (H.265 CRF26)",     ["-c:v", "libx265", "-preset", "medium",
                                    "-crf", "26", "-c:a", "aac", "-b:a", "160k"]),
    ("仅复制流 (超快无重编码)",     ["-c", "copy"]),
    ("自定义…",                    "__custom__"),
],
"audio": [
    ("默认 (192k)",               []),
    ("高质量 (320k)",              ["-b:a", "320k"]),
    ("低码率 (96k)",               ["-b:a", "96k"]),
    ("小体积 (64k)",               ["-b:a", "64k"]),
    ("语音压缩 (64k 单声道)",      ["-ac", "1", "-b:a", "64k"]),
    ("自定义…",                    "__custom__"),
],
"image": [
    ("默认",                       []),
    ("高压缩",                     ["-q:v", "8"]),
    ("缩放 512px 宽",              ["-vf", "scale=512:-1:flags=lanczos"]),
    ("自定义…",                    "__custom__"),
],
"m3u8": [
    ("默认 (复制流)",              []),
    ("自定义…",                    "__custom__"),
],
}


# 各媒体类型的默认初始格式
DEFAULT_FMT = {"video": "mp4", "audio": "mp3", "image": "jpg", "m3u8": "mp4"}
